config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #Create Read Update Delete
  #verb 'path', to: 'controller#action'

  # #See all the restaurants
  # get '/restaurants', to: 'restaurants#index'

  # #See details about a specif restaurant
  # get '/restaurants/:id', to: 'restaurants#show'

  # #Create a new restaurant
  # get '/restaurants/new', to: 'restaurants#new' # to display the form
  # post '/restaurants', to: 'restaurant#create'

  # #Update a restaurant
  # get '/restaurants/:id/edit', to: 'restaurants#edit'
  # patch 'restaurants/:id', to: 'restaurants#update'

  # #Delete a restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy'

  resources :restaurants

end

# routes -> controller -> view

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :rating, inclusion: { in: 1..5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new #needed to instantiate the form
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Check all the restaurants</h1>


<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
  </li>

  <% end %>


</ul>

app/views/restaurants/new.html.erb
<!-- <form action="/restaurants" method="post">

  <label for="name">Name</label>
  <input type="text" name="restaurant[name]">
  <label for="address">Address</label>
  <input type="text" name="restaurant[address]">
  <label for="rating">Rating</label>
  <input type="numeric" name="restaurant[rating]">
  <input type="submit">


</form> -->

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %>  </h1>

<h2> <%= @restaurant.rating %> Stars</h2>
<h2> <%= @restaurant.address %> </h2>

<!-- link_to text, path -->
<%= link_to "Edit Restaurant",  edit_restaurant_path(@restaurant)%>
<%= link_to "Delete",  restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" }%>